config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get "signup", to: 'users#new'
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories, except: [:destroy]
  # For details on the DSL available within this file, see
  # https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence:true, length: {minimum: 6, maximum:150}
  validates :description, presence:true, length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :cat_name, presence: true, length: {minimum: 5, maximum: 25}
  validates_uniqueness_of :cat_name, :message => '%{value} has already been taken'



  HUMANIZED_COLUMNS = {:cat_name => 'Category name'}

  def self.human_attribute_name(attribute, options = {})
    HUMANIZED_COLUMNS[attribute.to_sym] || super
  end

  Category.human_attribute_name("cat_name")
end

app/models/user.rb
class User < ApplicationRecord
before_save { self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
            uniqueness: { case_sensitive: false},
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false},
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# this would make the function available in controllers, not just views
  helper_method :current_user, :logged_in?

  def current_user
  @current_user ||=  User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "Please login to perform this action"
      redirect_to login_path
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show

  end

  def index
    @page_name = 'Article Listings'
    @article_list = Article.paginate(page: params[:page], per_page: 5 )
  end

  def new
    @page_name = 'Create New Article'
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @page_name = 'Edit Article'
  end

  def update

    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :genre, category_ids: [])
  end

  def require_same_user
    if (current_user != @article.user) && (!current_user.admin?)
      flash[:alert] = "You could only edit or delete your own articles"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category #{@category.cat_name} is successfully added to the app"
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    # @page_name = @category.cat_name
    @article_list = @category.articles.paginate(page: params[:page], per_page: 5 )
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category #{@category.cat_name} was updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @page_name = 'Categories'
    @category_list = Category.paginate(page: params[:page], per_page: 5 )
  end

  private

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform this action"
      redirect_to categories_path
    end
  end


  def category_params
    params.require(:category).permit(:cat_name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
    @page_name = 'About'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @page_name = 'Log In to Alpha BLog'
  end

  def create
    # byebug
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Hi, #{user.username}! Welcome back!"
      redirect_to user
    else
      flash.now[:alert] = "Username and password combination does not match our records"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index, :new, :create]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @page_name = 'Sign up for Alpha BLog'
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Hi, #{@user.username}! Welcome to the Alpha Blog, you have successfully signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @page_name = 'Edit User Information'
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Hey #{@user.username}, your information was updated successfully"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @page_name = 'Our Authors'
    @user_list = User.paginate(page: params[:page], per_page: 5 )
  end

  def show
    @article_list = @user.articles.paginate(page: params[:page], per_page: 5 )
  end

  def destroy
    @name = @user.username
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "The user #{@name} and their associated articles were successfully deleted"
    redirect_to root_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if (current_user != @user) && (!current_user.admin?)
      flash[:alert] = "You could only edit or delete your own profile details"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 200})
    # get the email from URL-parameters or what have you and make lowercase
    email_address = user.email.downcase

    # create the md5 hash
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    # compile URL which can be used in <img src="RIGHT_HERE"...
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @article_list.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8">
      <div class="container text-center shadow mt-4" id='container-about'>
        <div class="card-header regular-text-s">
          By <%= link_to article.user.username, article.user, class: "regular-text-s" %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-bold" %></h5>
          <div class="card-text text-left index-card-lr"><%= simple_format(truncate(article.description, length: 100, separator: ' ') { link_to "(more)", article_path(article), class: "text-bold" }) %></div>
          <p class="card-text regular-text-s">
            <i>Tags: </i>
            <% if article.categories.any? %>
              <%= render article.categories %>
            <% end %>
          </p>

          <p>
            <%= link_to image_tag("UI Icons_expand.png", height: "50", alt: "View Article"), article_path(article) %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to image_tag("UI Icons_edit.png", height: "50", alt: "Edit Article"), edit_article_path(article) %>
              <%= link_to image_tag("UI Icons_delete.png", height: "50",
                alt: "Delete Article"), article_path(article), method: :delete,
                data: {confirm: "Are you sure you want to delete article #{article.title}?"} %>
            <% end %>
          </p>

        </div>
        <div class="card-footer text-muted">
          <small>
            Created <%= time_ago_in_words(article.created_at) %> ago,
            Updated <%= time_ago_in_words(article.updated_at) %> ago
          </small>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="container" id="container-about">
  <%= render 'layouts/alpha_blog_logo_header' %>
</div>
<%= render 'shared/errors', obj: @article %>


<%= form_with(model: @article, local: true) do |f| %>
  <div class="spacious-15" id='container-about'>
    <div class="row">
      <div class="col-sm form-group regular-text">
        <%= f.label :title  %><br>
        <%= f.text_field :title, class: "form-control", placeholder: "title your article" %>
      </div>

    </div>
    <div class="form-group regular-text">
      <%= f.label :description %> <br>
      <%= f.text_area :description, rows:7, class: "form-control", placeholder: 'Write your article here' %>
    </div>

    <div class="form-group regular-text">
      <%= f.label :category %> <br>
      <%= f.collection_select(:category_ids, Category.all, :id, :cat_name,
          {prompt: "Choose your categories (or not)"}, { multiple: true, size:5, class: "custom-select form-control" } ) %>
    </div>
  </div>

  <div class="container" id='container-buttons'>
    <div class="row">
      <div class="col-sm">
        <a class="btn btn-primary nav-link btn-100" href=<%= articles_path %> role="button">cancel and return back to articles</a>
      </div>
      <div class="col-sm">
        <%= f.submit "Save Article", class: "btn btn-primary nav-link submit-btn", style: "height:100%; width:100%" %>
      </div>
    </div>
  </div>

<% end %>

app/views/articles/deprecated/index_table.html.erb
<div class="container" id="container-about">
  <%= render 'layouts/alpha_blog_logo_header' %>
</div>
<div class="container" id="container-about">
  <h1>Articles listings</h1>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Genre</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @article_list.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= article.genre %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete,
          data: { confirm: "Are you sure you want to delete article #{article.title}?" } %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
      </tr>
      <% end %>
    </tbody>

  </table>
  <p><%= link_to 'Create New Article', new_article_path  %></p>
</div>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container" id="container-about">
  <%= render 'layouts/alpha_blog_logo_header' %>
</div>
<div class="row justify-content-md-center">
  <div class="col-8">
    <a class="btn btn-primary nav-link shadow mt-4" href=<%= new_article_path  %> role="button">Create New Article</a>
  </div>
</div>


<div class="apple_pagination container pagination justify-content-center mt-4 regular-text-s">
  <%= will_paginate @article_list %>
</div>
<%= render 'article' %>

<div class="apple_pagination container pagination justify-content-center top-space mt-4 regular-text-s">
  <%= will_paginate @article_list %>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container" id="container-about">
  <%= render 'layouts/alpha_blog_logo_header' %>
</div>

<div class="row justify-content-md-center">
  <div class="col-8">
    <div class="container text-center shadow mt-4" id='container-about'>
      <div class="card-header regular-text-s">
        By <%= @article.user.username %>
      </div>
      <div class="card-body">
        <div class="row d-flex justify-content-center">
          <div class="col-2">
            <%= link_to gravatar_for(@article.user, size: 75), @article.user %>
          </div>
          <div class="col-10 justify-content-center align-self-center">
            <h5 class="text-bold text-left"><%= @article.title %></h5>
          </div>
        </div>
        <div class="card-text text-left regular-text-s" id='top-space'>
          <%= simple_format(@article.description) %>
        </div>
        <p class="card-text regular-text-s">
          <i>Tags: </i>
          <% if @article.categories.any? %>
            <%= render @article.categories %>
          <% end %>
        </p>
      </div>
        <div class="card-footer text-muted"> <small> Created
        <%= time_ago_in_words(@article.created_at) %> ago, Updated <%=
        time_ago_in_words(@article.updated_at) %> ago </small> </div> </div>
        </div> </div>



<div class="row justify-content-md-center mt-3">
  <div class="col-8">
    <div class="row justify-content-md-center">
      <div class="col-sm">
        <a class="btn btn-primary nav-link" href=<%= articles_path %> role="button">Back to articles</a>
      </div>
      <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
        <div class="col-sm">
          <a class="btn btn-primary nav-link" href=<%= edit_article_path(@article) %> role="button">Edit</a>
        </div>
        <div class="col-sm">
          <%= link_to 'Delete', article_path(@article), method: :delete,
            data: { confirm: "Are you sure you want to delete article #{@article.title}?" }, class: 'btn btn-primary nav-link' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.cat_name, category, class: "badge badge-light regular-text-s" %>

app/views/categories/_display_categories.html.erb
<% @category_list.each do |category| %>
  <div class="row justify-content-md-center">
    <div class="col-8">
      <div class="container text-center shadow mt-4" id='container-about'>

        <div class="card-body">
          <h5 class="card-title text-bold text-center"><%= link_to category.cat_name, category_path(category), class: "card-title text-bold text-left" %></h5>
          <%= pluralize(category.articles.count, 'article') %>
        </div>
        <div class="card-footer text-muted">
          <small>
            Created <%= time_ago_in_words(category.created_at) %> ago
          </small>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>


<%= form_with(model: @category, local: true) do |f| %>
  <div class="row justify-content-md-center">
    <div class="col-8 text-center">
      <div class="spacious-rl-160" id='container-about'>
        <div class="form-group regular-text">
          <%= f.label :cat_name, "Name the category"  %><br>
          <%= f.text_field :cat_name, class: "form-control text-center", placeholder: "enter name of category" %>
        </div>


      </div>
    </div>
  </div>

  <div class="row justify-content-md-center">
    <div class="col-8">
      <div class="container" id='container-buttons'>
        <div class="row">
          <div class="col-sm">
            <a class="btn btn-primary nav-link btn-100" href=<%= categories_path %> role="button">cancel and return back to categories</a>
          </div>
          <div class="col-sm">
            <%= f.submit(@category.new_record? ? "Save Category" : "Update", class: "btn btn-primary nav-link submit-btn", style: "height:100%; width:100%") %>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/categories/edit.html.erb
<div class="container" id="container-about">
  <%= render 'layouts/alpha_blog_logo_header' %>
</div>

<div class="row justify-content-md-center">
  <div class="col-4">
    <a class="btn btn-primary nav-link shadow mt-4" href=<%= category_path(@category)  %> role="button">cancel and return back to <%= @category.cat_name %></a>
  </div>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="container" id="container-about">
  <%= render 'layouts/alpha_blog_logo_header' %>
</div>


<div class="apple_pagination container pagination justify-content-center mt-4 regular-text-s">
  <%= will_paginate @category_list %>
</div>

<%= render 'display_categories' %>

<div class="apple_pagination container pagination justify-content-center mt-4 regular-text-s">
  <%= will_paginate @category_list %>
</div>

app/views/categories/new.html.erb
<div class="container" id="container-about">
  <%= render 'layouts/alpha_blog_logo_header' %>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="container justify-content-center mt-4 alpha-blog-logo">
  <%= @category.cat_name %>
</div>
<% if logged_in? && current_user.admin? %>
  <div class="row justify-content-md-center">
    <div class="col-8">
      <a class="btn btn-primary nav-link shadow mt-4" href=<%= edit_category_path(@category)  %> role="button">Edit</a>
    </div>
  </div>
<% end %>

<div class="apple_pagination container pagination justify-content-center mt-4 regular-text-s">
  <%= will_paginate @article_list %>
</div>

<%= render 'articles/article' %>

<div class="apple_pagination container pagination justify-content-center mt-4 regular-text-s">
  <%= will_paginate @article_list %>
</div>

app/views/layouts/_alpha_blog_logo_header.html.erb
<!-- <div class="container" id = 'container-home'> -->
  <div class="jumbotron">
    <h1 class="alpha-blog-logo">ALPHA BLOG</h1>
    <h2 class="alpha-blog-logo-it">FINALLY, YOUR CREATIVE OUTLET</h2>
  </div>
<!-- </div> -->

app/views/layouts/_footer.html.erb
<footer id='sticky-footer' class='py-4 text-white-50'>
  <div class="container-fluid">
    <div class="row">
      <div class="col-2">
      </div>
      <div class="col-sm text-center" id ='text-bottom'>
        <br>
        <small>Made with Ruby on Rails by Maria Vaghani | New York</small>
      </div>
      <div class="col-2">
        <p id='links-footer'>
          <%= link_to image_tag("icons8-github-100.png", size: "60x60", alt: "GitHub Maria Vaghani"), "https://github.com/mariavaghani" %>
          <%= link_to image_tag("icons8-linkedin-100.png", size: "60x60", alt: "LinkedIn Maria Vaghani"), "https://www.linkedin.com/in/maria-vaghani/" %>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link font-weight-bold" aria-current="page" href=<%=root_path%>>Alpha Blog</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Content
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href=<%=users_path %>>Our Authors</a></li>
            <li><a class="dropdown-item" href=<%=articles_path %>>All Articles</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href=<%=categories_path %>>All Categories</a></li>
            <% if logged_in? && current_user.admin? %>
              <li><a class="dropdown-item" href=<%=new_category_path %>>Create New Category</a></li>
            <% end %>
          </ul>
        </li>

        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "[admin]" if current_user.admin? %>
              <%= current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href=<%=user_path(current_user) %>>User Profile</a></li>
              <li><a class="dropdown-item" href=<%=edit_user_path(current_user) %>>Edit User Info</a></li>

              <li><a class="dropdown-item" href=<%=new_article_path %>>Create New Article</a></li>
              <div class="dropdown-divider"></div>
              <li>
                <%= link_to 'Delete User Profile', user_path(current_user), method: :delete,
                  data: { confirm: "Are you sure you want to delete #{current_user.username}'s profile and all articles they created?" }, class: 'dropdown-item text-danger' %>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link font-weight-bold", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link font-weight-bold" %>
          </li>
          <li class="nav-item">
            <a class="nav-link font-weight-bold" aria-current="page" href=<%=login_path%>>Login</a>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link font-weight-bold" href="#" tabindex="-1" aria-disabled="true"><%= @page_name %></a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/pages/home.html.erb
<div class="container" id="container-home">
  <%= render 'layouts/alpha_blog_logo_header' %>
</div>

<div class="container" id='container-buttons'>
  <div class="row">
    <div class="col-sm">
      <a class="btn btn-primary nav-link" href=<%= about_path %> role="button">about</a>
    </div>
    <div class="col-sm">
      <a class="btn btn-primary nav-link" href=<%= users_path %> role="button">Our Authors</a>
    </div>
    <div class="col-sm">
      <a class="btn btn-primary nav-link" href=<%= signup_path %> role="button">Sign Up</a>
    </div>
    <div class="col-sm">
      <a class="btn btn-primary nav-link" href=<%= login_path %> role="button">login</a>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<% @user_list.each do |user| %>
  <div class="row justify-content-md-center">
    <div class="col-8">
      <div class="container text-center shadow mt-4" id='container-about'>
        <div class="card-header regular-text-s">
           User Profile
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-4">
              <%= link_to gravatar_for(user, size: 150), user %>
            </div>
            <div class="col-4">
              <h5 class="card-title text-bold text-left"><%= link_to user.username, user, class: "card-title text-bold text-left" %></h5>
              <div class="card-text text-left regular-text-s">
                <%= user.email %><br>
                <%= pluralize(user.articles.count, 'article') %>
              </div>
            </div>
            <div class="col-4">
              <%= link_to image_tag("UI Icons_expand.png", height: "45", alt: "View User Profile"), user %>
              <% if logged_in? && (user == current_user || current_user.admin?) %>
                <%= link_to image_tag("UI Icons_edit.png", height: "45", alt: "Edit User Details"), edit_user_path(user) %>
                <% if current_user.admin? %>
                  <%= link_to image_tag("UI Icons_delete.png", height: "45",
                    alt: "Delete User"), user_path(user), method: :delete,
                    data: {confirm: "Are you sure you want to delete #{user.username}'s user profile and all their articles?"} %>
                <% end %>
              <% end %>
            </div>
          </div>

        </div>
        <div class="card-footer text-muted">
          <small>
            Joined <%= time_ago_in_words(user.created_at) %> ago
          </small>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container" id="container-about">
  <%= render 'layouts/alpha_blog_logo_header' %>
</div>


<div class="row justify-content-md-center">
  <div class="col-8">
    <% if !logged_in? %>
      <a class="btn btn-primary nav-link shadow mt-4" href=<%= signup_path  %> role="button">Sign Up</a>
    <% else %>
      <a class="btn btn-primary nav-link shadow mt-4" href=<%= user_path(current_user)  %> role="button">[ <%= current_user.username %> ] User Profile</a>
    <% end %>
  </div>
</div>

<div class="apple_pagination container pagination justify-content-center mt-4 regular-text-s">
  <%= will_paginate @user_list %>
</div>

<%= render 'user' %>

<div class="apple_pagination container pagination justify-content-center mt-4 regular-text-s">
  <%= will_paginate @user_list %>
</div>

app/views/users/show.html.erb
<div class="container" id="container-about">
  <%= render 'layouts/alpha_blog_logo_header' %>
</div>

<div class="row justify-content-md-center">
  <div class="col-8">
    <div class="container text-center shadow mt-4" id='container-about'>
      <div class="card-header regular-text-s">
         User Profile
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-4" id="right-space">
            <%= gravatar_for @user %>
          </div>
          <div class="col-8">
            <h5 class="card-title text-bold text-left"><%= @user.username %></h5>
            <div class="card-text text-left regular-text-s">
              <%= @user.email %>
            </div>
          </div>
        </div>
      </div>
      <div class="card-footer text-muted">
        <small>
          Created <%= time_ago_in_words(@user.created_at) %> ago,
          Updated <%= time_ago_in_words(@user.updated_at) %> ago
        </small>
      </div>
    </div>
  </div>
</div>


<div class="row justify-content-md-center mt-3">
  <div class="col-8">
    <div class="row justify-content-md-center">
      <div class="col-5">
        <a class="btn btn-primary nav-link" href=<%= articles_path %> role="button">Back to articles</a>
      </div>
      <% if logged_in? && @user == current_user %>
        <div class="col-5">
          <a class="btn btn-primary nav-link" href=<%= edit_user_path(@user) %> role="button">Edit Profile Details</a>
        </div>
        <div class="col-2">
          <%= link_to 'Delete', user_path(@user), method: :delete,
            data: { confirm: "Are you sure you want to delete #{@user.username}'s user profile and all their articles?" }, class: 'btn btn-primary nav-link' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="apple_pagination container pagination justify-content-center mt-4 regular-text-s">
  <%= will_paginate @article_list %>
</div>

<%= render 'articles/article' %>

<div class="apple_pagination container pagination justify-content-center mt-4 regular-text-s">
  <%= will_paginate @article_list %>
</div>